name = "FuzzCraft 4"
author = "FuzzyMelon94"
version = "0.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c80b7a12bc2016643ea0125e0004e571148e8d8bfcca86972a3826bedb9525e3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
